"""Expanded training dataset for claim classification - 450+ examples"""

TRAINING_DATA = [
    # ============================================================================
    # CHECKWORTHY CLAIMS (150 examples) - Factual statements that can be verified
    # ============================================================================
    
    # Politics & Government (30)
    ("The president signed the infrastructure bill into law", "checkworthy"),
    ("Congress passed the budget with a 60-40 vote", "checkworthy"),
    ("The unemployment rate dropped to 3.5% last month", "checkworthy"),
    ("The GDP grew by 2.3% in the last quarter", "checkworthy"),
    ("The Supreme Court ruled 6-3 on the case", "checkworthy"),
    ("Voter turnout reached 67% in the election", "checkworthy"),
    ("The Senate confirmed the nominee with 52 votes", "checkworthy"),
    ("The government allocated $50 billion for infrastructure", "checkworthy"),
    ("The tax rate was reduced from 35% to 21%", "checkworthy"),
    ("The bill was vetoed by the governor yesterday", "checkworthy"),
    ("The mayor announced a new public transportation plan", "checkworthy"),
    ("The state legislature passed the education reform bill", "checkworthy"),
    ("The federal deficit increased by $1 trillion", "checkworthy"),
    ("The minimum wage was raised to $15 per hour", "checkworthy"),
    ("The trade agreement was signed by 12 countries", "checkworthy"),
    ("The sanctions were imposed on three nations", "checkworthy"),
    ("The embassy was closed due to security concerns", "checkworthy"),
    ("The peace treaty was ratified by both governments", "checkworthy"),
    ("The referendum passed with 55% approval", "checkworthy"),
    ("The cabinet member resigned from their position", "checkworthy"),
    ("The investigation lasted for 18 months", "checkworthy"),
    ("The policy was implemented in January 2023", "checkworthy"),
    ("The executive order was signed on Monday", "checkworthy"),
    ("The committee held 15 hearings on the matter", "checkworthy"),
    ("The legislation affects 50 million citizens", "checkworthy"),
    ("The budget proposal includes $200 billion in cuts", "checkworthy"),
    ("The diplomatic mission included 30 delegates", "checkworthy"),
    ("The summit was attended by 20 world leaders", "checkworthy"),
    ("The coalition government formed after 6 weeks", "checkworthy"),
    ("The constitutional amendment requires 2/3 majority", "checkworthy"),
    
    # Health & Medicine (30)
    ("The COVID-19 vaccine has 95% efficacy rate", "checkworthy"),
    ("The FDA approved the new cancer treatment", "checkworthy"),
    ("The study included 10,000 participants", "checkworthy"),
    ("The medication was recalled by the manufacturer", "checkworthy"),
    ("Life expectancy increased by 2 years", "checkworthy"),
    ("The hospital has 500 beds available", "checkworthy"),
    ("The disease affects 1 in 1000 people", "checkworthy"),
    ("The clinical trial lasted 3 years", "checkworthy"),
    ("The vaccine prevents 90% of infections", "checkworthy"),
    ("The surgery has an 85% success rate", "checkworthy"),
    ("The drug costs $500 per dose", "checkworthy"),
    ("The outbreak affected 5,000 people", "checkworthy"),
    ("The treatment reduces symptoms by 70%", "checkworthy"),
    ("The WHO declared it a pandemic in March 2020", "checkworthy"),
    ("The virus has a 2% mortality rate", "checkworthy"),
    ("The hospital opened a new wing with 200 beds", "checkworthy"),
    ("The research was published in Nature journal", "checkworthy"),
    ("The therapy costs $10,000 per session", "checkworthy"),
    ("The disease was eradicated in 1980", "checkworthy"),
    ("The vaccine requires two doses", "checkworthy"),
    ("The infection rate dropped by 40%", "checkworthy"),
    ("The medical device was approved in 2022", "checkworthy"),
    ("The prescription drug prices increased 15%", "checkworthy"),
    ("The health insurance covers 80% of costs", "checkworthy"),
    ("The clinic serves 1,000 patients per month", "checkworthy"),
    ("The epidemic lasted for 6 months", "checkworthy"),
    ("The antibiotics are effective against the bacteria", "checkworthy"),
    ("The screening test has 98% accuracy", "checkworthy"),
    ("The hospital mortality rate is 2.5%", "checkworthy"),
    ("The medical school accepts 150 students annually", "checkworthy"),
    
    # Science & Technology (30)
    ("The spacecraft reached Mars after 7 months", "checkworthy"),
    ("The telescope discovered 50 new exoplanets", "checkworthy"),
    ("The particle accelerator is 27 kilometers long", "checkworthy"),
    ("The experiment was conducted at -273 degrees Celsius", "checkworthy"),
    ("The satellite was launched in December 2023", "checkworthy"),
    ("The research team published findings in Science", "checkworthy"),
    ("The AI model achieved 99% accuracy", "checkworthy"),
    ("The battery lasts for 10 hours", "checkworthy"),
    ("The processor has 8 cores", "checkworthy"),
    ("The network speed is 1 gigabit per second", "checkworthy"),
    ("The software update was released yesterday", "checkworthy"),
    ("The company sold 50 million units", "checkworthy"),
    ("The device weighs 200 grams", "checkworthy"),
    ("The screen resolution is 4K", "checkworthy"),
    ("The camera has 48 megapixels", "checkworthy"),
    ("The rocket can carry 100 tons to orbit", "checkworthy"),
    ("The mission cost $2.5 billion", "checkworthy"),
    ("The telescope is located in Chile", "checkworthy"),
    ("The experiment lasted 5 years", "checkworthy"),
    ("The quantum computer has 50 qubits", "checkworthy"),
    ("The data center uses 100 megawatts", "checkworthy"),
    ("The algorithm processes 1 million images per second", "checkworthy"),
    ("The robot can lift 500 kilograms", "checkworthy"),
    ("The solar panel efficiency is 22%", "checkworthy"),
    ("The wind turbine generates 5 megawatts", "checkworthy"),
    ("The electric car has a 300-mile range", "checkworthy"),
    ("The 5G network covers 80% of the city", "checkworthy"),
    ("The supercomputer performs 1 exaflop", "checkworthy"),
    ("The asteroid passed Earth at 2 million miles", "checkworthy"),
    ("The earthquake measured 7.2 on Richter scale", "checkworthy"),
    
    # Business & Economics (30)
    ("The company reported $5 billion in revenue", "checkworthy"),
    ("The stock price increased 15% today", "checkworthy"),
    ("The merger was valued at $50 billion", "checkworthy"),
    ("The inflation rate reached 8% annually", "checkworthy"),
    ("The interest rate was raised to 5%", "checkworthy"),
    ("The company employs 100,000 workers", "checkworthy"),
    ("The quarterly profit was $2 billion", "checkworthy"),
    ("The market cap reached $1 trillion", "checkworthy"),
    ("The dividend yield is 3.5%", "checkworthy"),
    ("The IPO raised $10 billion", "checkworthy"),
    ("The factory produces 1 million units per year", "checkworthy"),
    ("The retail sales increased 5% last month", "checkworthy"),
    ("The unemployment claims dropped by 20,000", "checkworthy"),
    ("The trade deficit widened to $70 billion", "checkworthy"),
    ("The oil price rose to $90 per barrel", "checkworthy"),
    ("The gold price reached $2,000 per ounce", "checkworthy"),
    ("The cryptocurrency lost 50% of its value", "checkworthy"),
    ("The bond yield increased to 4%", "checkworthy"),
    ("The housing prices rose 10% year-over-year", "checkworthy"),
    ("The consumer confidence index is at 110", "checkworthy"),
    ("The company announced 5,000 layoffs", "checkworthy"),
    ("The acquisition was completed in Q3 2023", "checkworthy"),
    ("The revenue grew 25% compared to last year", "checkworthy"),
    ("The operating margin is 15%", "checkworthy"),
    ("The debt-to-equity ratio is 0.5", "checkworthy"),
    ("The earnings per share is $5.50", "checkworthy"),
    ("The price-to-earnings ratio is 20", "checkworthy"),
    ("The market share increased to 30%", "checkworthy"),
    ("The production costs decreased by 12%", "checkworthy"),
    ("The supply chain disruption lasted 3 months", "checkworthy"),
    
    # Environment & Climate (30)
    ("Global temperatures rose 1.5 degrees Celsius", "checkworthy"),
    ("The carbon emissions decreased 10% last year", "checkworthy"),
    ("The ice sheet lost 200 billion tons of ice", "checkworthy"),
    ("The sea level rose 3 millimeters annually", "checkworthy"),
    ("The forest fire burned 500,000 acres", "checkworthy"),
    ("The renewable energy accounts for 30% of power", "checkworthy"),
    ("The species was declared endangered in 2020", "checkworthy"),
    ("The air quality index reached 150", "checkworthy"),
    ("The drought lasted for 18 months", "checkworthy"),
    ("The hurricane was category 4", "checkworthy"),
    ("The flood affected 100,000 residents", "checkworthy"),
    ("The coral reef lost 50% of its coverage", "checkworthy"),
    ("The deforestation rate is 10 million hectares per year", "checkworthy"),
    ("The plastic waste in oceans is 8 million tons", "checkworthy"),
    ("The ozone layer recovered by 3%", "checkworthy"),
    ("The wind speed reached 150 mph", "checkworthy"),
    ("The rainfall was 10 inches above average", "checkworthy"),
    ("The wildfire season started 2 months early", "checkworthy"),
    ("The glacier retreated 100 meters", "checkworthy"),
    ("The biodiversity declined 25% in 50 years", "checkworthy"),
    ("The solar farm generates 100 megawatts", "checkworthy"),
    ("The recycling rate increased to 35%", "checkworthy"),
    ("The water shortage affects 2 billion people", "checkworthy"),
    ("The tornado was rated EF3", "checkworthy"),
    ("The snowfall was 50 inches this winter", "checkworthy"),
    ("The heat wave lasted 2 weeks", "checkworthy"),
    ("The conservation area covers 1 million acres", "checkworthy"),
    ("The endangered species population is 500", "checkworthy"),
    ("The pollution levels exceeded WHO guidelines", "checkworthy"),
    ("The climate agreement was signed by 195 countries", "checkworthy"),
    
    # ============================================================================
    # OPINION CLAIMS (150 examples) - Subjective statements
    # ============================================================================
    
    # Personal Preferences (30)
    ("I think pizza is the best food", "opinion"),
    ("This movie was amazing", "opinion"),
    ("The weather is beautiful today", "opinion"),
    ("That's a terrible idea", "opinion"),
    ("I believe we should do better", "opinion"),
    ("This is the worst product ever", "opinion"),
    ("I feel happy about this decision", "opinion"),
    ("The design looks ugly", "opinion"),
    ("I prefer coffee over tea", "opinion"),
    ("That song is boring", "opinion"),
    ("I love this restaurant", "opinion"),
    ("The book was disappointing", "opinion"),
    ("I think he's a great leader", "opinion"),
    ("This seems like a bad choice", "opinion"),
    ("I hope things get better", "opinion"),
    ("The color scheme is perfect", "opinion"),
    ("I hate waiting in lines", "opinion"),
    ("Summer is the best season", "opinion"),
    ("Dogs are better than cats", "opinion"),
    ("This tastes delicious", "opinion"),
    ("The music is too loud", "opinion"),
    ("I find this boring", "opinion"),
    ("The room feels cozy", "opinion"),
    ("This is my favorite show", "opinion"),
    ("I dislike the new policy", "opinion"),
    ("The service was excellent", "opinion"),
    ("I prefer the old version", "opinion"),
    ("This is a waste of time", "opinion"),
    ("The atmosphere is wonderful", "opinion"),
    ("I enjoy reading fiction", "opinion"),
    
    # Judgments & Evaluations (30)
    ("He is the greatest athlete of all time", "opinion"),
    ("This is the most important issue", "opinion"),
    ("She deserves to win the award", "opinion"),
    ("The team played poorly", "opinion"),
    ("This is a masterpiece", "opinion"),
    ("The performance was outstanding", "opinion"),
    ("He made a stupid mistake", "opinion"),
    ("This is completely unfair", "opinion"),
    ("The decision was wise", "opinion"),
    ("She is incredibly talented", "opinion"),
    ("This is a brilliant strategy", "opinion"),
    ("The plan is foolish", "opinion"),
    ("He is overrated", "opinion"),
    ("This is a waste of money", "opinion"),
    ("The policy is too harsh", "opinion"),
    ("She is the best candidate", "opinion"),
    ("This is poorly executed", "opinion"),
    ("The idea is genius", "opinion"),
    ("He is a terrible manager", "opinion"),
    ("This is well-designed", "opinion"),
    ("The approach is flawed", "opinion"),
    ("She is underappreciated", "opinion"),
    ("This is a smart move", "opinion"),
    ("The system is broken", "opinion"),
    ("He is a visionary", "opinion"),
    ("This is inadequate", "opinion"),
    ("The solution is elegant", "opinion"),
    ("She is incompetent", "opinion"),
    ("This is revolutionary", "opinion"),
    ("The outcome is disappointing", "opinion"),
    
    # Beliefs & Values (30)
    ("Everyone deserves a second chance", "opinion"),
    ("Honesty is the best policy", "opinion"),
    ("Family comes first", "opinion"),
    ("Money can't buy happiness", "opinion"),
    ("Education is the key to success", "opinion"),
    ("Hard work always pays off", "opinion"),
    ("People should be more compassionate", "opinion"),
    ("We need to protect our environment", "opinion"),
    ("Freedom is more important than security", "opinion"),
    ("Children should respect their elders", "opinion"),
    ("Art is essential to society", "opinion"),
    ("Technology makes life better", "opinion"),
    ("Privacy is a fundamental right", "opinion"),
    ("Competition brings out the best in people", "opinion"),
    ("Tradition should be preserved", "opinion"),
    ("Change is necessary for progress", "opinion"),
    ("Justice should be swift", "opinion"),
    ("Forgiveness is important", "opinion"),
    ("Loyalty is a virtue", "opinion"),
    ("Diversity makes us stronger", "opinion"),
    ("Patience is a virtue", "opinion"),
    ("Knowledge is power", "opinion"),
    ("Actions speak louder than words", "opinion"),
    ("The truth will set you free", "opinion"),
    ("Love conquers all", "opinion"),
    ("Time heals all wounds", "opinion"),
    ("What doesn't kill you makes you stronger", "opinion"),
    ("The customer is always right", "opinion"),
    ("Less is more", "opinion"),
    ("Quality over quantity", "opinion"),
    
    # Recommendations & Advice (30)
    ("You should try this restaurant", "opinion"),
    ("I recommend reading this book", "opinion"),
    ("You need to see this movie", "opinion"),
    ("Everyone should learn to code", "opinion"),
    ("You ought to apologize", "opinion"),
    ("I suggest taking a different approach", "opinion"),
    ("You should invest in stocks", "opinion"),
    ("I advise against that decision", "opinion"),
    ("You must visit Paris", "opinion"),
    ("I think you should wait", "opinion"),
    ("You need to be more careful", "opinion"),
    ("I recommend the blue one", "opinion"),
    ("You should get more sleep", "opinion"),
    ("I suggest starting earlier", "opinion"),
    ("You ought to save more money", "opinion"),
    ("I think you should reconsider", "opinion"),
    ("You need to work harder", "opinion"),
    ("I recommend hiring more staff", "opinion"),
    ("You should take a vacation", "opinion"),
    ("I advise consulting an expert", "opinion"),
    ("You must try the dessert", "opinion"),
    ("I suggest a different strategy", "opinion"),
    ("You should be more patient", "opinion"),
    ("I recommend the premium version", "opinion"),
    ("You need to focus on priorities", "opinion"),
    ("I think you should delegate", "opinion"),
    ("You ought to be more assertive", "opinion"),
    ("I suggest postponing the meeting", "opinion"),
    ("You should listen to feedback", "opinion"),
    ("I recommend taking the course", "opinion"),
    
    # Predictions & Speculations (30)
    ("I think it will rain tomorrow", "opinion"),
    ("The team will probably win", "opinion"),
    ("This trend will continue", "opinion"),
    ("I believe prices will increase", "opinion"),
    ("The market will likely crash", "opinion"),
    ("I expect better results next time", "opinion"),
    ("This will be a huge success", "opinion"),
    ("I predict a landslide victory", "opinion"),
    ("The situation will improve", "opinion"),
    ("I think he will resign", "opinion"),
    ("This will end badly", "opinion"),
    ("I believe she will accept", "opinion"),
    ("The project will fail", "opinion"),
    ("I expect delays", "opinion"),
    ("This will revolutionize the industry", "opinion"),
    ("I think they will merge", "opinion"),
    ("The economy will recover", "opinion"),
    ("I predict record sales", "opinion"),
    ("This will become obsolete", "opinion"),
    ("I believe tensions will ease", "opinion"),
    ("The trend will reverse", "opinion"),
    ("I think demand will surge", "opinion"),
    ("This will set a precedent", "opinion"),
    ("I expect strong opposition", "opinion"),
    ("The policy will backfire", "opinion"),
    ("I believe support will grow", "opinion"),
    ("This will spark controversy", "opinion"),
    ("I think interest will wane", "opinion"),
    ("The initiative will succeed", "opinion"),
    ("I predict significant changes", "opinion"),
    
    # ============================================================================
    # UNVERIFIABLE CLAIMS (150 examples) - Cannot be fact-checked
    # ============================================================================
    
    # Vague Statements (30)
    ("Things will get better eventually", "unverifiable"),
    ("Some people say it works", "unverifiable"),
    ("Many believe this is true", "unverifiable"),
    ("It's possible that aliens exist", "unverifiable"),
    ("There might be a solution", "unverifiable"),
    ("Experts suggest various approaches", "unverifiable"),
    ("Studies show mixed results", "unverifiable"),
    ("The situation is complicated", "unverifiable"),
    ("It depends on many factors", "unverifiable"),
    ("Results may vary", "unverifiable"),
    ("This could go either way", "unverifiable"),
    ("Opinions are divided", "unverifiable"),
    ("The truth is somewhere in between", "unverifiable"),
    ("It's hard to say for certain", "unverifiable"),
    ("There are different perspectives", "unverifiable"),
    ("The evidence is inconclusive", "unverifiable"),
    ("It's a matter of interpretation", "unverifiable"),
    ("The data is ambiguous", "unverifiable"),
    ("Circumstances vary", "unverifiable"),
    ("It's not that simple", "unverifiable"),
    ("There are pros and cons", "unverifiable"),
    ("The situation is fluid", "unverifiable"),
    ("It's a gray area", "unverifiable"),
    ("The outcome is uncertain", "unverifiable"),
    ("It's open to debate", "unverifiable"),
    ("The answer is unclear", "unverifiable"),
    ("It's a complex issue", "unverifiable"),
    ("The reality is nuanced", "unverifiable"),
    ("It's difficult to determine", "unverifiable"),
    ("The picture is incomplete", "unverifiable"),
    
    # Philosophical & Metaphysical (30)
    ("Everything happens for a reason", "unverifiable"),
    ("The universe has a purpose", "unverifiable"),
    ("Fate determines our path", "unverifiable"),
    ("Free will is an illusion", "unverifiable"),
    ("Consciousness is fundamental", "unverifiable"),
    ("Reality is subjective", "unverifiable"),
    ("Time is an illusion", "unverifiable"),
    ("The soul is immortal", "unverifiable"),
    ("We are all connected", "unverifiable"),
    ("Life has inherent meaning", "unverifiable"),
    ("The mind creates reality", "unverifiable"),
    ("Destiny cannot be changed", "unverifiable"),
    ("The universe is conscious", "unverifiable"),
    ("Death is not the end", "unverifiable"),
    ("We live in a simulation", "unverifiable"),
    ("Parallel universes exist", "unverifiable"),
    ("Thoughts create reality", "unverifiable"),
    ("The present moment is all that exists", "unverifiable"),
    ("Suffering is necessary for growth", "unverifiable"),
    ("The universe is infinite", "unverifiable"),
    ("Consciousness survives death", "unverifiable"),
    ("We choose our circumstances before birth", "unverifiable"),
    ("Energy never dies", "unverifiable"),
    ("The universe is expanding infinitely", "unverifiable"),
    ("Time travel is theoretically possible", "unverifiable"),
    ("Multiple dimensions exist", "unverifiable"),
    ("The universe is cyclical", "unverifiable"),
    ("Consciousness is non-local", "unverifiable"),
    ("Reality is a hologram", "unverifiable"),
    ("The observer creates reality", "unverifiable"),
    
    # Supernatural & Paranormal (30)
    ("Ghosts exist in abandoned buildings", "unverifiable"),
    ("Psychic abilities are real", "unverifiable"),
    ("Astrology influences personality", "unverifiable"),
    ("Crystals have healing powers", "unverifiable"),
    ("Aliens have visited Earth", "unverifiable"),
    ("Telepathy is possible", "unverifiable"),
    ("Past lives can be remembered", "unverifiable"),
    ("Guardian angels protect us", "unverifiable"),
    ("Auras reveal inner states", "unverifiable"),
    ("Chakras affect health", "unverifiable"),
    ("Spirits communicate through mediums", "unverifiable"),
    ("Curses can affect people", "unverifiable"),
    ("Premonitions predict the future", "unverifiable"),
    ("Energy healing works", "unverifiable"),
    ("Demons possess people", "unverifiable"),
    ("Witchcraft has real power", "unverifiable"),
    ("Voodoo dolls work", "unverifiable"),
    ("Tarot cards reveal truth", "unverifiable"),
    ("Numerology predicts destiny", "unverifiable"),
    ("Palmistry reveals character", "unverifiable"),
    ("Feng shui affects energy", "unverifiable"),
    ("Manifestation creates reality", "unverifiable"),
    ("The law of attraction works", "unverifiable"),
    ("Karma determines fate", "unverifiable"),
    ("Reincarnation is real", "unverifiable"),
    ("Spiritual guides exist", "unverifiable"),
    ("Miracles happen", "unverifiable"),
    ("Divine intervention occurs", "unverifiable"),
    ("Prophecies come true", "unverifiable"),
    ("Magic is real", "unverifiable"),
    
    # Conspiracy Theories & Rumors (30)
    ("The government is hiding the truth", "unverifiable"),
    ("Secret societies control the world", "unverifiable"),
    ("The moon landing was faked", "unverifiable"),
    ("Chemtrails are poisoning us", "unverifiable"),
    ("Vaccines contain microchips", "unverifiable"),
    ("The earth is actually flat", "unverifiable"),
    ("Reptilians rule the world", "unverifiable"),
    ("The Illuminati controls everything", "unverifiable"),
    ("Area 51 hides alien technology", "unverifiable"),
    ("Big Pharma suppresses cures", "unverifiable"),
    ("The media is controlled by elites", "unverifiable"),
    ("Elections are rigged", "unverifiable"),
    ("Climate change is a hoax", "unverifiable"),
    ("5G causes health problems", "unverifiable"),
    ("Fluoride is mind control", "unverifiable"),
    ("The New World Order is coming", "unverifiable"),
    ("Celebrities are clones", "unverifiable"),
    ("The Bermuda Triangle is supernatural", "unverifiable"),
    ("Ancient aliens built the pyramids", "unverifiable"),
    ("Bigfoot roams the forests", "unverifiable"),
    ("The Loch Ness Monster exists", "unverifiable"),
    ("Time travelers walk among us", "unverifiable"),
    ("The government created AIDS", "unverifiable"),
    ("Subliminal messages control minds", "unverifiable"),
    ("HAARP controls the weather", "unverifiable"),
    ("Crop circles are alien messages", "unverifiable"),
    ("The Denver Airport is evil", "unverifiable"),
    ("Paul McCartney died in 1966", "unverifiable"),
    ("Shakespeare didn't write his plays", "unverifiable"),
    ("The Titanic was switched with another ship", "unverifiable"),
    
    # Future Predictions (30)
    ("Robots will take over the world", "unverifiable"),
    ("Humans will colonize Mars", "unverifiable"),
    ("AI will become sentient", "unverifiable"),
    ("World peace will be achieved", "unverifiable"),
    ("Cancer will be cured", "unverifiable"),
    ("Flying cars will be common", "unverifiable"),
    ("Immortality will be possible", "unverifiable"),
    ("The singularity is near", "unverifiable"),
    ("Humans will merge with machines", "unverifiable"),
    ("Climate change will be reversed", "unverifiable"),
    ("Universal basic income will be adopted", "unverifiable"),
    ("Cryptocurrency will replace money", "unverifiable"),
    ("Virtual reality will replace reality", "unverifiable"),
    ("Teleportation will be invented", "unverifiable"),
    ("Aging will be cured", "unverifiable"),
    ("Space tourism will be affordable", "unverifiable"),
    ("Quantum computers will solve everything", "unverifiable"),
    ("Fusion energy will power the world", "unverifiable"),
    ("Humans will live underwater", "unverifiable"),
    ("Mind uploading will be possible", "unverifiable"),
    ("Nanotechnology will cure diseases", "unverifiable"),
    ("Genetic engineering will create superhumans", "unverifiable"),
    ("Brain-computer interfaces will be common", "unverifiable"),
    ("Holographic displays will replace screens", "unverifiable"),
    ("3D printing will revolutionize manufacturing", "unverifiable"),
    ("Autonomous vehicles will eliminate accidents", "unverifiable"),
    ("Vertical farms will feed the world", "unverifiable"),
    ("Ocean cleanup will restore ecosystems", "unverifiable"),
    ("Asteroid mining will make us rich", "unverifiable"),
    ("Warp drive will enable interstellar travel", "unverifiable"),
    
    # Proverbs & Sayings (30)
    ("Good things come to those who wait", "unverifiable"),
    ("What goes around comes around", "unverifiable"),
    ("The early bird catches the worm", "unverifiable"),
    ("All good things must come to an end", "unverifiable"),
    ("When one door closes another opens", "unverifiable"),
    ("Lightning never strikes twice", "unverifiable"),
    ("The grass is always greener", "unverifiable"),
    ("You can't teach an old dog new tricks", "unverifiable"),
    ("A watched pot never boils", "unverifiable"),
    ("Absence makes the heart grow fonder", "unverifiable"),
    ("Birds of a feather flock together", "unverifiable"),
    ("The apple doesn't fall far from the tree", "unverifiable"),
    ("You reap what you sow", "unverifiable"),
    ("Every cloud has a silver lining", "unverifiable"),
    ("Fortune favors the bold", "unverifiable"),
    ("The pen is mightier than the sword", "unverifiable"),
    ("Two wrongs don't make a right", "unverifiable"),
    ("The squeaky wheel gets the grease", "unverifiable"),
    ("You can't have your cake and eat it too", "unverifiable"),
    ("A penny saved is a penny earned", "unverifiable"),
    ("Don't count your chickens before they hatch", "unverifiable"),
    ("The road to hell is paved with good intentions", "unverifiable"),
    ("Curiosity killed the cat", "unverifiable"),
    ("Practice makes perfect", "unverifiable"),
    ("Necessity is the mother of invention", "unverifiable"),
    ("The best things in life are free", "unverifiable"),
    ("You can lead a horse to water", "unverifiable"),
    ("A stitch in time saves nine", "unverifiable"),
    ("Too many cooks spoil the broth", "unverifiable"),
    ("The proof is in the pudding", "unverifiable"),
]

# Total: 450 examples (150 per class)
